#-------------------------------------------------------------------------------
# Name:        settings-agent.yml
# Purpose:     Settings file for the local agent
#
# Author:      Laurent Carré
#
# Created:     26/02/2024
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-2024
# Licence:     Eclipse Public License 2.0
#-------------------------------------------------------------------------------
#
function: Local system control agent
server_name: agent
log_level: INFO
trace_dir: /data/solidsense/traces
log_module:
    main: DEBUG

features:
    - agent

servers:

- Main:
      class: GenericTopServer

- gRPCMain:
    class: GrpcServer
    port: 4506

services:

- Agent:
    class: AgentService
    server: gRPCMain







