#-------------------------------------------------------------------------------
# Name:        settings-agent.yml
# Purpose:     Settings file for the local agent
# Compatibility: Version 2.0
#
# Author:      Laurent Carré
#
# Created:     16/10/2023
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-2024
# Licence:     Eclipse Public License 2.0
#-------------------------------------------------------------------------------
#
function: Navigation messages router
server_name: navigation_router
log_level: INFO
log_module:
    router_core.console: INFO
features:
    - router_core
    - nmea2000
    - couplers:
          - ShipModulConfig
          - ShipModulInterface
          - GrpcNmeaCoupler


servers:

- Main:
      class: NavigationMainServer

- NMEAServer:
    class: NMEAServer
    port: 4500
    nmea2000: dyfmt

- NMEASender:
    class: NMEASenderServer
    port: 4503
    coupler: MiniPlex3
    max_silent: 10

- gRPCMain:
    class: GrpcServer
    port: 4502

- ShipModulConfig:
    class: ShipModulConfig
    port: 4501
    coupler: MiniPlex3

- NMEANetwork:
    class: NMEA2KController

couplers:

- MiniPlex3:
    class: ShipModulInterface
    address: 172.16.2.100
    port: 10110
    nmea2000_controller: NMEANetwork
    protocol: nmea2000
    
- EnergyInput:
    class: GrpcNmeaCoupler
    server: gRPCMain

services:

- Console:
    class: Console
    server: gRPCMain

publishers:

- SendNMEA2000:
    class: GrpcPublisher
    active: true
    decode_nmea2000: false
    nmea0183: convert_strict
    address: 127.0.0.1
    port: 4508
    max_retry: 0
    filters: [Engine]
    couplers: [MiniPlex3]

filters:

- RaymarineProprietary:
    class: NMEA2000Filter
    pgn: [126720]
    type: discard


- Engine:
      class: NMEA2000Filter
      pgn: [127488, 127489]
      type: select

