#-------------------------------------------------------------------------------
# Name:        settings-agent.yml
# Purpose:     Settings file for the local agent
#
# Author:      Laurent Carré
#
# Created:     26/02/2024
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-2024
# Licence:     Eclipse Public License 2.0
#-------------------------------------------------------------------------------
#
function: Local system control agent
server_name: navigation_agent

log_level: INFO
log_module:

features:
    - agent


servers:

- Main:
    class: GenericTopServer

- gRPCMain:
    class: GrpcServer
    port: 4506

services:

- Agent:
    class: AgentService
    server: gRPCMain







