#-------------------------------------------------------------------------------
# Name:        settings.yml
# Purpose:     Settings file for the navigation server
#
# Author:      Laurent Carré
#
# Created:     26/12/2021
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-2022
# Licence:     <your licence>
#-------------------------------------------------------------------------------
#
log_level: INFO
trace_dir: /mnt/meaban/Bateau/tests
log_module:
  IPInstrument: INFO
  ydn2k_instrument: INFO

servers:


instruments:

- ScannavReplay:
    class: NMEA2000TCPReader
    address: 192.168.1.21
    port: 3555
    transport: TCP
    # server: NMEAServer
    direction: read_only
    # white_list: [GGA, GLL, RMC]
    # black_list: [PGN]
    report_timer: 60

- YDEthernet:
    class: YDInstrument
    address: 192.168.1.60
    port: 1457
    transport: TCP
    protocol: nmea2000
    direction: bidirectional
    trace_messages: true

publishers:

- EthInjector:
      class: Injector
      instruments: [ScannavReplay]
      target: YDEthernet
      queue_size: 50
      max_lost: 20


#    - MainLog:
#       class: LogPublisher
#        file: /data/solidsense/log/navigation.log
#        instruments: [MiniPlex3]






