#-------------------------------------------------------------------------------
# Name:        settings.yml
# Purpose:     Settings file for the navigation server
#
# Author:      Laurent Carré
#
# Created:     26/12/2021
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-2022
# Licence:     Eclipse Public License 2.0
#-------------------------------------------------------------------------------
#
log_level: INFO
trace_dir: /mnt/meaban/Bateau/tests
log_module:
    nmea_routing.message_server: DEBUG

servers:

- NMEAServer:
    class: NMEAServer
    port: 4500

- NMEASender:
    class: NMEASenderServer
    port: 4503
    coupler: MiniPlex3
    max_silent: 10
    master: 192.168.1.21

- Console:
    class: Console
    port: 4502

- ShipModulConfig:
    class: ShipModulConfig
    port: 4501
    coupler: MiniPlex3

couplers:

#- Serial1:
 #    class: NMEASerialPort
 #    device: /dev/ttyUSB1
  #  baudrate: 57600
  #   server: NMEAServer
   #  trace_messages: false

- MiniPlex3:
    class: ShipModulInterface
    address: 192.168.1.25
    port: 10110
    transport: TCP
    server: NMEAServer
    trace_messages: true


publishers:

#    - MainLog:
#       class: LogPublisher
#        file: /data/solidsense/log/navigation.log
#        instruments: [MiniPlex3]






