#-------------------------------------------------------------------------------
# Name:        settings.yml
# Purpose:     Settings file for the navigation server
#
# Author:      Laurent Carré
#
# Created:     26/12/2021
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-2022
# Licence:     <your licence>
#-------------------------------------------------------------------------------
#
log_level: INFO
trace_dir: /mnt/meaban/Bateau/tests
# log_file: test_fast_packet
log_module:
  nmea_routing.coupler: INFO
  nmea2000.nmea2000_msg: INFO
  nmea2000.nmea2k_controller: INFO
  nmea2000.nmea2k_active_controller: DEBUG
  nmea2000.nmea2k_device: INFO
  nmea2000.nmea2k_application: DEBUG
  nmea2000.n2k_name: INFO
  nmea2000.nmea2k_can_interface: INFO

servers:

- NMEAServer:
      class: NMEAServer
      port: 4500
      nmea2000: dyfmt

- Console:
      class: Console
      port: 4502

- NMEANetwork:
      class: NMEA2KActiveController
      trace: false
      channel: can0

- NMEAOutput:
    class: NMEASenderServer
    port: 4503
    nmea2000: dyfmt
    coupler: CAN

- NMEAOutput:
    class: NMEASenderServer
    port: 4503
    nmea2000: dyfmt
    coupler: CAN


couplers:

- CAN:
    class: DirectCANCoupler
    autostart: true
    nmea2000_controller: NMEANetwork

filters:

- FastPacket:
    class: NMEA2000Filter
    pgn: [129029, 126996, 129540]
    action: select

- RaymarineProprietary:
    class: NMEA2000Filter
    pgn: [126720]
    action: select

- NMEASent:
    class: NMEA2000Filter
    pgn: [129025, 129026, 129283, 129284]
    action: select

data_sinks:

- DataAnalyzer:
      class: NMEADataClient

publishers:

- TraceRaymarine:
    class: N2KTracePublisher
    filters: [RaymarineProprietary]
    output: PRINT

- TraceOutput:
    class: N2KTracePublisher
    filters: [NMEASent]


