#-------------------------------------------------------------------------------
# Name:        settings.yml
# Purpose:     Settings file for the navigation server
#
# Author:      Laurent Carré
#
# Created:     26/12/2021
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-2022
# Licence:     <your licence>
#-------------------------------------------------------------------------------
#
trace: DEBUG
trace_dir: /mnt/meaban/Bateau/tests

servers:
- NMEAServer:
    class: NMEA_server
    port: 4500

- Console:
    class: Console
    port: 4502

couplers:

- GPS:
    class: InternalGps
    trace_messages: true

publishers:







