#-------------------------------------------------------------------------------
# Name:        settings-agent.yml
# Purpose:     Settings file for the local agent
#
# Author:      Laurent Carré
#
# Created:     16/10/2023
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-2024
# Licence:     Eclipse Public License 2.0
#-------------------------------------------------------------------------------
#
log_level: INFO
trace_dir: /mnt/meaban/Bateau/tests
log_module:
    nmea_routing.console: INFO


servers:

- NMEAServer:
    class: NMEAServer
    port: 4500
    nmea2000: dyfmt

- NMEASender:
    class: NMEASenderServer
    port: 4503
    coupler: MiniPlex3
    max_silent: 10

- gRPCMain:
    class: GrpcServer
    port: 4502

- ShipModulConfig:
    class: ShipModulConfig
    port: 4501
    coupler: MiniPlex3

- NMEANetwork:
    class: NMEA2KController

couplers:

- MiniPlex3:
    class: ShipModulInterface
    address: 172.16.2.100
    port: 10110
    nmea2000_controller: NMEANetwork
    protocol: nmea2000

services:

- Console:
    class: Console
    server: gRPCMain

filters:

- RaymarineProprietary:
    class: NMEA2000Filter
    pgn: [126720]
    action: discard


publishers:







