#-------------------------------------------------------------------------------
# Name:        settings.yml
# Purpose:     Settings file for the navigation server
#
# Author:      Laurent Carré
#
# Created:     26/12/2021
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-2022
# Licence:     <your licence>
#-------------------------------------------------------------------------------
#
log_level: INFO
trace_dir: /mnt/meaban/Bateau/tests
# log_file: test_fast_packet
log_module:
  nmea_routing.IPCoupler: INFO
  nmea_routing.coupler: INFO
  nmea_routing.nmea2000_msg: INFO
  nmea_routing.ydn2k_coupler: INFO
  nmea2000.nmea2k_controller: INFO
  nmea2000.n2k_name: INFO
  nmea2000.nmea2k_pgndefs: INFO
  nmea2000.nmea2k_encode_decode: INFO

servers:

- Console:
      class: Console
      port: 4602

- NMEANetwork:
      class: NMEA2KController


couplers:

- LogReader:
    class: RawLogCoupler
    logfile: /mnt/meaban/Bateau/tests/TRACE-MiniPlex3-230720-0644.log
    autostart: true
    nmea2000_controller: NMEANetwork
    protocol: nmea2000
    direction: read_only

filters:


data_clients:

- DataSender:
      class: NMEAGrpcDataClient
      address: 127.0.0.1
      port: 4601

publishers:


