#-------------------------------------------------------------------------------
# Name:        settings.yml
# Purpose:     Settings file for the navigation server
#
# Author:      Laurent Carré
#
# Created:     26/12/2021
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-2022
# Licence:     <your licence>
#-------------------------------------------------------------------------------
#
trace: INFO

servers:

- NMEAServer:
    class: NMEA_server
    port: 4500

- Console:
    class: Console
    port: 4502

- ShipModulConfig:
    class: ShipModulConfig
    port: 4501
    instrument: MiniPlex3

instruments:

- MiniPlex3:
    class: ShipModulInterface
    address: 172.16.2.100
    port: 10110
    transport: TCP
    server: NMEAServer

- SolarPanel:
    class: MPPT_Instrument
    port: 4505
    server: NMEAServer
    direction: read_only
    report_timer: 10

- GPS:
    class: InternalGps
    server: NMEAServer

publishers:

#    - MainLog:
#       class: LogPublisher
#        file: /data/solidsense/log/navigation.log
#        instruments: [MiniPlex3]






