#-------------------------------------------------------------------------------
# Name:        settings.yml
# Purpose:     Settings file for the navigation server
#
# Author:      Laurent Carré
#
# Created:     26/12/2021
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-2022
# Licence:     Eclipse Public License 2.0
#-------------------------------------------------------------------------------
#
log_level: INFO
trace_dir: /mnt/meaban/Bateau/tests
log_module:
    data_server: INFO
    instrument: INFO
    nmea2k_pgndefs: INFO
    shipmodul_if: INFO
    ikonvert: INFO



servers:

- NMEAServer:
    class: NMEAServer
    port: 4500
    sender: iKonvert1
    nmea2000: transparent
    master: 192.168.1.21

- Console:
    class: Console
    port: 4502

- ShipModulConfig:
    class: ShipModulConfig
    port: 4501
    coupler: MiniPlex3

- NMEASender:
    class: NMEASenderServer
    port: 4503
    coupler: MiniPlex3
    max_silent: 10
    master: 192.168.1.21

couplers:

- iKonvert1:
    class: iKonvert
    device: /dev/ttyUSB1
    protocol: nmea2000
    autostart: false

- MiniPlex3:
    class: ShipModulInterface
    address: 192.168.1.16
    port: 10110
    transport: TCP
    server: NMEAServer

publishers:

#- Trace:
#    class: N2KTracePublisher
#    instruments: [MiniPlex3]
#   queue_size: 40
#   filter: [129540]


#    - MainLog:
#       class: LogPublisher
#        file: /data/solidsense/log/navigation.log
#        instruments: [MiniPlex3]






