#-------------------------------------------------------------------------------
# Name:        settings.yml
# Purpose:     Settings file for the navigation server
# Compatibility: Version 2.0
#
# Author:      Laurent Carré
#
# Created:     01/02/2024
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-202#
# Licence:     Eclipse Public License 2.0
#-------------------------------------------------------------------------------
#
#  Settings file for the test configuration involving
#  A NMEA0183 Log replay program (ScannavReplay) running a machine sending a mix NMEA2000 (PDGY) and NMEA0183 messages
#  message server running on a RPi with a direct connection to a NMEA2000 bus
#
# The message server is performing the following operations
#  read NMEA0183 messages from the replay server using the NMEATCPReader 'SNReplay'
#  conversion of NMEA0183 sentences in NMEA2000
#  injecting the messages (via the Injector 'CanFeed') on the CAN NMEA2000 bus through the DirectCANCoupler 'InputCoupler'
#  remark: 'DecodedInput' application is not used in this case as it takes decoded NMEA2000 in Protobuf format as input

function: Scannav replay to CAN injection
log_level: INFO
trace_dir: /mnt/meaban/Bateau/tests

log_module:
  can_interface.nmea2k_application: INFO
  can_interface.nmea2k_can_interface: INFO

features:
  - router_core
  - nmea2000
  - can_interface
  - couplers:
      - NMEATCPReader


servers:

- Main:
    class: NavigationMainServer

- gRPCMainServer:
      class: GrpcServer
      port: 4502

- NMEANetwork:
      class: NMEA2KActiveController
      trace: false
      channel: can0
      max_silent: 60.0
      applications: [InputCoupler, DecodedInput]

couplers:

- InputCoupler:
    class: DirectCANCoupler

- SNReplay:
    class: NMEATCPReader
    address: 192.168.1.21
    port: 3555
    autostart: true
    protocol: nmea2000
    nmea0183_convert: true
    trace_messages: false
    trace_raw: false

filters:

- NMEAOutput:
    class: NMEA2000Filter
    pgn: [129283, 129284, 129285, 126992, 130074]
    type: select

- AIS:
    class: NMEA2000Filter
    pgn: [129794, 129810, 129809]
    type: select

services:

- Console:
    class: Console
    server: gRPCMainServer

publishers:

- TraceOutput:
    class: N2KTracePublisher
    couplers: [InputCoupler]
    filters: [NMEAOutput]
    filter_select: true
    active: true
    flexible_decode: false

- CanFeed:
    class: Injector
    target: InputCoupler
    couplers: [SNReplay]
    active: true

applications:

- DecodedInput:
    class: GrpcInputApplication
    server: gRPCMainServer





