#-------------------------------------------------------------------------------
# Name:        settings.yml
# Purpose:     Settings file for the navigation server
#
# Author:      Laurent Carré
#
# Created:     16/10/2023
# Copyright:   (c) Laurent Carré Sterwen Technology 2021-2024
# Licence:     Eclipse Public License 2.0
#-------------------------------------------------------------------------------
#
log_level: INFO
trace_dir: /mnt/meaban/Bateau/tests
log_module:

features:
    - router_core
    - nmea2000
    - nmea0183
    - couplers:
          - ShipModulConfig
          - ShipModulInterface

servers:

- NMEAServer:
    class: NMEAServer
    port: 4500
    nmea2000: dyfmt

- NMEASender:
    class: NMEASenderServer
    port: 4503
    coupler: MiniPlex3
    max_silent: 10

- gRPCMain:
    class: GrpcServer
    port: 4502

- ShipModulConfig:
    class: ShipModulConfig
    port: 4501
    coupler: MiniPlex3

- NMEANetwork:
    class: NMEA2KController

couplers:

- MiniPlex3:
    class: Shipmodul
    address: 192.168.1.31
    port: 10110
    nmea2000_controller: NMEANetwork
    protocol: nmea2000

services:

- Console:
    class: Console
    server: gRPCMain

filters:

- FastPacket:
    class: NMEA2000Filter
    pgn: [129029, 126996, 129540]
    type: select

- RaymarineProprietary:
    class: NMEA2000Filter
    pgn: [126720]
    type: select

- NMEASent:
    class: NMEA2000Filter
    pgn: [129025, 129026, 129283, 129284]
    type: select


publishers:

- TraceOutput:
    class: N2KTracePublisher
    filters: [NMEASent]
    couplers: [iKonvertCoupler]
    active: false





